[target.arm-unknown-linux-gnueabihf]
image = "local/armhf-image:latest"

[target.aarch64-unknown-linux-gnu]
image = "local/aarch64-image:latest"

[target.i686-pc-windows-gnu]
image = "rustembedded/cross:i686-pc-windows-gnu"