on:
  pull_request:
  push:
    branches:
      - '**'

name: Compile for everything

jobs:
  build_win:
    name: Build for Windows
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - i686-pc-windows-gnu
          - x86_64-pc-windows-gnu
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - run: strip -s ${{ github.workspace }}/target/${{ matrix.target }}/release/network-client.exe
      - run: mv ${{ github.workspace }}/target/${{ matrix.target }}/release/network-client.exe ${{ github.workspace }}/target/${{ matrix.target }}/release/network-client-${{ matrix.target }}.exe

      - uses: actions/upload-artifact@master
        with:
          name: network-client-windows ${{ matrix.target }}
          path: ${{ github.workspace }}/target/${{ matrix.target }}/release/network-client-${{ matrix.target }}.exe

  build_linux_armhf:
    name: Build for Linux armhf
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: sudo docker build -t local/armhf-image:latest -f ${{ github.workspace }}/.github/scripts/Dockerfile_armhf .

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: arm-unknown-linux-gnueabihf
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=arm-unknown-linux-gnueabihf

      - run: sudo apt-get update
      - run: sudo apt-get install --assume-yes binutils-arm-linux-gnueabihf
      - run: /usr/bin/arm-linux-gnueabihf-strip -s ${{ github.workspace }}/target/arm-unknown-linux-gnueabihf/release/network-client
      - run: mv ${{ github.workspace }}/target/arm-unknown-linux-gnueabihf/release/network-client ${{ github.workspace }}/target/arm-unknown-linux-gnueabihf/release/network-client-linux-armhf

      - uses: actions/upload-artifact@master
        with:
          name: network-client-linux-armhf
          path: ${{ github.workspace }}/target/arm-unknown-linux-gnueabihf/release/network-client-linux-armhf

  build_linux_aarch64:
    name: Build for Linux aarch64
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: sudo docker build -t local/aarch64-image:latest -f ${{ github.workspace }}/.github/scripts/Dockerfile_aarch64 .

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=aarch64-unknown-linux-gnu

      - run: sudo apt-get update
      - run: sudo apt-get install --assume-yes binutils-aarch64-linux-gnu
      - run: /usr/bin/aarch64-linux-gnu-strip  -s ${{ github.workspace }}/target/aarch64-unknown-linux-gnu/release/network-client
      - run: mv ${{ github.workspace }}/target/aarch64-unknown-linux-gnu/release/network-client ${{ github.workspace }}/target/aarch64-unknown-linux-gnu/release/network-client-linux-aarch64

      - uses: actions/upload-artifact@master
        with:
          name: network-client-linux-aarch64
          path: ${{ github.workspace }}/target/aarch64-unknown-linux-gnu/release/network-client-linux-aarch64

  build_linux_amd64:
    name: Build for Linux amd64
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - run: sudo apt-get update
      - run: sudo apt-get install -y libudev-dev

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-unknown-linux-gnu

      - run: strip -s ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/network-client
      - run: mv ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/network-client ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/network-client-linux-amd64

      - uses: actions/upload-artifact@master
        with:
          name: network-client-linux-x64
          path: ${{ github.workspace }}/target/x86_64-unknown-linux-gnu/release/network-client-linux-amd64
